name: Build and Release

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build for multiple platforms
      if: github.event_name == 'release'
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o katana-linux-amd64
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o katana-linux-arm64
        
        # Linux 386
        GOOS=linux GOARCH=386 go build -o katana-linux-386
    
    - name: Upload Release Assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./katana-linux-amd64
        asset_name: katana-linux-amd64
        asset_content_type: application/octet-stream
